server:
  port: 8082
spring:
  application:
    name: product-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
niws:
  loadbalancer:
    availabilityFilteringRule:
      filterCircuitTripped: false